version: 2
updates:
  - package-ecosystem: gomod
    directory: /companion
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: /nexus
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: /bff
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /console
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 2
