version: 2
updates:
  - package-ecosystem: gomod
    directory: /v2/companion
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: /v2/nexus
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: /v2/bff
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /v2/console
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: /v2
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 2
