FROM node:22.12-bookworm AS node-runtime

FROM mcr.microsoft.com/playwright:v1.61.1-noble

COPY --from=node-runtime /usr/local /usr/local

WORKDIR /app

COPY console/package*.json ./
RUN npm ci

COPY console/ ./
