FROM node:22.12-alpine

WORKDIR /app
COPY console/package*.json ./
RUN npm install

COPY console/ ./
RUN chown -R node:node /app
USER node

EXPOSE 19173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
